config/routes.rb
Rails.application.routes.draw do

  get 'activities/by_categories', to: 'activities#by_categories'

  resources :activities
  resources :activity_types

  #  RtillaWork: Customize Devise controller route after its updated
  # devise_for :users, controllers: {  sessions: 'users/sessions' }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'users/registrations' }

  #  RtillaWork: add /start and /stop routes for Controller#start and Controller#stop methods

  get 'welcome/home'
  get 'welcome/about'

  root to: 'welcome#home'

end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :authenticate_admin!
  before_action :authenticate_user!
  before_action :set_activity_type, only: [:show, :edit, :update, :destroy]

  # GET /activity_types
  def index
    @activity_types = ActivityType.all
  end

  # GET /activity_types/1
  def show
  end

  # GET /activity_types/new
  def new
    @activity_type = ActivityType.new
  end

  # GET /activity_types/1/edit
  def edit
  end

  # POST /activity_types
  def create
    @activity_type = ActivityType.new(activity_type_params)

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /activity_types/1
  def update
    respond_to do |format|
      if @activity_type.update(activity_type_params)
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /activity_types/1
  def destroy
    @activity_type.destroy
    respond_to do |format|
      format.html { redirect_to activity_types_url, notice: 'Activity type was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity_type
    @activity_type = ActivityType.find(params[:id])
  end

  # Only allow the white list through.
  def activity_type_params
    params.require(:activity_type).permit(:name, :fa_icon, :alt_icon, :category, :intensity)
  end
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/views/activity_types/_form.html.erb
<%= form_with(model: activity_type, local: true) do |form| %>
  <% if activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
        <% activity_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :fa_icon %>
    <%= form.text_field :fa_icon %>
  </div>

  <div class="field">
    <%= form.label :alt_icon %>
    <%= form.text_field :alt_icon %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :intensity %>
    <%= form.text_field :intensity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activity_types/edit.html.erb
<h1>Editing Activity Type</h1>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Show', @activity_type %> |
<%= link_to 'Back', activity_types_path %>

app/views/activity_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activity Types</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Fa icon</th>
    <th>Alt icon</th>
    <th>Category</th>
    <th>Intensity</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @activity_types.each do |activity_type| %>
    <tr>
      <td><%= activity_type.name %></td>
      <td><%= activity_type.fa_icon %></td>
      <td><%= activity_type.alt_icon %></td>
      <td><%= activity_type.category %></td>
      <td><%= activity_type.intensity %></td>
      <td><%= link_to 'Show', activity_type %></td>
      <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
      <td><%= link_to 'Destroy', activity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity Type', new_activity_type_path %>

app/views/activity_types/new.html.erb
<h1>New Activity Type</h1>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity_type.name %>
</p>

<p>
  <strong>Fa icon:</strong>
  <%= @activity_type.fa_icon %>
</p>

<p>
  <strong>Alt icon:</strong>
  <%= @activity_type.alt_icon %>
</p>

<p>
  <strong>Category:</strong>
  <%= @activity_type.category %>
</p>

<p>
  <strong>Intensity:</strong>
  <%= @activity_type.intensity %>
</p>

<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>