config/routes.rb
Rails.application.routes.draw do

  get 'activities/by_categories', to: 'activities#by_categories'

  resources :activities
  resources :activity_types

  #  RtillaWork: Customize Devise controller route after its updated
  # devise_for :users, controllers: {  sessions: 'users/sessions' }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'users/registrations' }

  #  RtillaWork: add /start and /stop routes for Controller#start and Controller#stop methods

  get 'welcome/home'
  get 'welcome/about'

  root to: 'welcome#home'

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :activity_type

  # def self.activity_in_progress
  # 	Activity.find_by(:end_time == nil)
  # end

  #  RtillaWork: current activity (last one non nil) for current_user OR nil = no current activity
  # return ongoing current activity or nil WARNING replace .nil? with .blank? or better .empty? when used

  # scope :user_current_activity, -> { where(user_id: current_user.id, duration: nil).order(start_time: :desc).limit(1).first if  user_signed_in?}

  # return  the lastest completed activity, WARNING same as above
  # scope :user_previous_activity, -> { where(user_id: current_user.id).where.not(duration: nil).order(start_time: :desc).limit(1).first if  user_signed_in?}

  # scope :all_activities_by_type, -> (activity_type) { current_user.activities.where(user_id: current_user.id, activity_type: activity_type.id).order(start_time: :desc) if  user_signed_in? }

  # scope :all_activities_by_type, -> (activity_type) { where(user_id: current_user.id, activity_type: activity_type.id).order(start_time: :desc) if  user_signed_in? }

end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
  has_many :activities, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_activity_types

  # GET /activities  
  def index
    @current_activity = user_current_activity
    @previous_activity = user_previous_activity
    @all_activities_same_date = all_activities_by_date
    @all_activities_same_type = all_activities_by_type

    if @current_activity.nil? && @previous_activity.nil?
      # first time login
      redirect_to new_activity_path and return
    elsif !@current_activity.nil?
      # ongoing current activity
      redirect_to action: :edit, id: @current_activity.id
    else
      # @activities = Activity.all
      @activities = current_user.activities
    end
  end

  def by_categories
    @current_activity = user_current_activity
    @previous_activity = user_previous_activity
    @all_activities_same_date = all_activities_by_date
    @all_activities_same_type = all_activities_by_type

    if @current_activity.nil? && @previous_activity.nil?
      # first time login
      redirect_to new_activity_path and return
    elsif !@current_activity.nil?
      # ongoing current activity
      redirect_to action: :edit, id: @current_activity.id
    else
      # @activities = Activity.all
      @activities = current_user.activities
    end
  end

  # GET /activities/1
  def show
    @current_activity = user_current_activity
    if !@current_activity.nil?
      # ongoing current activity
      redirect_to action: :edit, id: @current_activity.id
    else
      # @activity as routed
      @activity
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)
    # current_user.activities << @activity
    if @activity.save
      redirect_to @activity, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update

    #  RtillaWork: ensuring end_time, duration = ni, nil OR duration = end_time - start_time
    # updated_activity = @activity.dup
    # updated_activity.attributes = activity_params
    #@activity.attributes = activity_params
    # if @activity.end_time.nil?  || (@activity.end_time.to_i < @activity.start_time.to_i)
    #   @activity.end_time , @activity.duration = nil, nil
    # else
    #   @activity.duration = Time.parse(@activity.end_time) - Time.parse(@activity.start_time)
    #   raise @activity.inspect
    #   # Debug redirect_to welcome_home_path and return
    # end
    # @activity = updated_activity.dup
    # if @activity.save
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
    if @activity.user_id == current_user.id
      @activity
    else
      redirect_to root_path, notice: 'DEBUG activity user id mismatch'
    end
  end

  # Only allow this white list params.
  def activity_params
    #  RtillaWork: user_id not included in .permit for added security
    # , as form_with would build parameters on all @activity fields
    #processed_params =
    params.require(:activity)
          .permit(:start_time, :duration, :activity_type_id)
          .merge(user_id: current_user.id)

    # if processed_params[:end_time].nil?  || (processed_params[:end_time].to_i < processed_params[:start_time].to_i)
    #   processed_params[:end_time] , processed_params[:duration] = nil, nil
    # else
    #   processed_params[:duration] =
    #   ( DateTime.parse(processed_params[:end_time]) - DateTime.parse(processed_params[:start_time]) )
    #   .to_s(:iso8601)
    # end

    #processed_params
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activity_verb_past_helper(activity_type_name)
    case activity_type_name
    when "Running"
      "ran"
    when "Walking"
      "walked"
    when "Cycling"
      "went cycling"
    when "Swimming"
      "swam"
    when "Strength Training"
      "trained"
    when "Hicking"
      "hicked"
    when "Nordic Skiing"
      "went nordic skiing"
    when "Skiing"
      "went skiing"
    when "Skating"
      "went skating"
    when "Snowboarding"
      "went snowboarding"
    when "Hockey"
      "played hocked"
    when "Table Tennis"
      "played table tennis"
    else
      "exercised"
    end
  end

  def activity_motivational_helper(duration)
    case duration
    when 0..15
      "Keep the Good Work!"
    when 15..60
      "Good Job!"
    when 60..120
      "Excellent!"
    else
      "Incredible! You might want to take a break :)"
    end
  end

  def compute_duration(datetime_end = DateTime.now, datetime_start = 0)
    # duration in minutes from seconds
    duration = ((datetime_end.to_i - datetime_start.to_i) / 60).round + 1
    # raise duration.inspect
  end

  def activity_picture_url(activity_name)
    # jpeg pic names based on activity_name.snake.tolow + '.jpg'
    # replace later with API
    case activity_name
    when "Running"
      "https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80"
    when "Walking"
      "https://images.unsplash.com/photo-1487956382158-bb926046304a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1502&q=80"
    when "Cycling"
      "https://images.unsplash.com/photo-1517649763962-0c623066013b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"
    when "Swimming"
      "https://images.unsplash.com/photo-1530549387789-4c1017266635?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"
    when "Strength Training"
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"
    when "Hicking"
      "https://images.unsplash.com/19/nomad.JPG?ixlib=rb-1.2.1&auto=format&fit=crop&w=1288&q=80"
    when "Nordic Skiing"
      "https://images.unsplash.com/photo-1518775053278-5a569f0be353?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80"
    when "Skiing"
      "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80"
    when "Skating"
      "https://images.unsplash.com/photo-1517177646641-83fe10f14633?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1608&q=80"
    when "Snowboarding"
      "https://images.unsplash.com/photo-1522445263200-1b4b91053db8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80"
    when "Hockey"
      "https://images.unsplash.com/photo-1545652034-ff9abf03cf70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80"
    when "Table Tennis"
      "https://images.unsplash.com/photo-1534158914592-062992fbe900?ixlib=rb-1.2.1&auto=format&fit=crop&w=1375&q=80"
    else
      # generic exercice pic
      "https://images.unsplash.com/photo-1484583066749-c2129489f52f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1490&q=80"
    end
  end

  def activity_css_rgba(activity)
    # duration 121 min max duration
    css_color_names = ["AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine", "Azure", "Beige", "Bisque", "Black", "BlanchedAlmond", "Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "CornflowerBlue", "Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGrey", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "Darkorange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray", "DarkSlateGrey", "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DimGrey", "DodgerBlue", "FireBrick", "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Grey", "Green", "GreenYellow", "HoneyDew", "HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender", "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray", "LightGrey", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSlateGrey", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "SlateGrey", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen"]
    css_color_names_length = css_color_names.length
    # r, g, b = activity.activity_type.name.bytes[0..2]
    # r, g, b = r - rand(16), g - rand(16), b - rand(16)
    # a = [activity.activity_type.name.bytes[3] + activity.duration + 128, 255].max
    # "background-color: rgba(#{r}, #{g}, #{b}, #{a})"
    css_color_names_index = rand(css_color_names_length -1)
    # raise (rand(r) + rand(g) + rand(b) + rand(a)).inspect
    # raise [css_color_names_length, css_color_names_index].inspect
    css_color_names[css_color_names_index].to_sym
  end

end

app/views/activities/_activity_card.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="shadow mb-3 rounded text-white" style="background-image:url(https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80); background-size: cover; background-position: center;">
        <div class="p-3 rounded d-flex justify-content-between flex-sm-row flex-column" style="background-color: rgba(0,0,0,0.5)">
          <div class="display-4">Running</div>
          <div class="d-flex align-items-center">
            <a href="#" class="btn btn-primary d-inline-block"><i class="fas fa-clock mr-2"></i> Start activity</a>
          </div>
        </div>
      </div>
      <div class="shadow mb-3 rounded text-white bg-center bg-cover" style="background-image:url(https://images.unsplash.com/photo-1520156676478-476f97cb33c7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1800&q=60);">
        <div class="p-3 rounded d-flex justify-content-between" style="background-color: rgba(0,0,0,0.5)">
          <div class="display-4">Swimming</div>
          <div class="d-flex align-items-center">
            <a href="#" class="btn btn-primary d-inline-block"><i class="fas fa-clock mr-2"></i> Start activity</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/_form.html.erb
<%= bootstrap_form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">

    <%# <%= form.label :name %>
    <%# <%= form.text_field :name %>

    <div class="btn-group-vertical">
      <div class="btn-group">
        <button type="button" class="btn btn-secondary">Running <i class="fas fa-running"></i></button>
        <button type="button" class="btn btn-secondary">Walking <i class="fas fa-walking"></i></button>
        <button type="button" class="btn btn-secondary">Cycling <i class="fas fa-bicycle"></i></button>
        <button type="button" class="btn btn-secondary">Swimming <i class="fas fa-swimming-pool"></i></button>
      </div>

      <div class="btn-group">
        <button type="button" class="btn btn-secondary">Weights <i class="fas fa-dumbbell"></i></button>
        <button type="button" class="btn btn-secondary">Hicking <i class="fas fa-hiking"></i></button>
        <button type="button" class="btn btn-secondary">Kendo <i class="fas fa-user-ninja"></i></button>
        <button type="button" class="btn btn-secondary">Nordic Skiing <i class="fas fa-skiing-nordic"></i></button>
      </div>

      <div class="btn-group">
        <button type="button" class="btn btn-secondary">Mountain Skiing <i class="fas fa-skiing"></i></button>
        <button type="button" class="btn btn-secondary">Mountain parkour <i class="fas fa-mountain"></i></button>
        <button type="button" class="btn btn-secondary">Skating <i class="fas fa-skating"></i></button>
        <button type="button" class="btn btn-secondary">Snowboarding <i class="fas fa-snowboarding"></i></button>
      </div>
    </div>

  </div>




  </div>


  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration %>
  </div>

  <%# <div class="field"> %>
  <%# <%= form.label :thumbnail %>
  <%# <%= form.text_field :thumbnail %>
  <%# </div> %>

  <%# <div class="field"> %>
  <%# <%= form.label :icon %>
  <%# <%= form.text_field :icon %>
  <%# </div> %>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>




















<%= bootstrap_form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :activity_type_id %>
    <%= form.text_field :activity_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/by_categories.html.erb
<%# provide(:@activity.activity_type.name) %>

<hgroup>
  <h1 class="text-right"><em>Activities count: <%= @activities.count %></em></h1>
</hgroup>

<%= link_to 'Show By Date', activities_path, class: "btn btn-md btn-info my-5 w-100" %>
<%= link_to 'New Activity', new_activity_path, class: "btn btn-md btn-success w-100" %>


<div class="d-flex flex-wrap">


  <%# @activities.each do |activity| %>
  <% @all_activities_same_type.each do |activity_type, same_activities| %>
    <div class="container my-1">
      <h2 class="display-2">
        <a class="btn btn-lg btn-primary w-25" data-toggle="collapse" href=<%= '#' + activity_type.name.to_s %>>
          <%= font_awesome_tag(activity_type.fa_icon, "10rem") %>  <%= activity_type.name %>
        </a>
      </h2>
    </div>

    <div class="collapse" id=<%= activity_type.name.to_s %>>

      <% same_activities.each do |activity| %>
        <%# [r, g, b, a] = activity_color_rgba(activity) %>
        <div class="container mb-3">
          <div class="row">
            <div class="col-lg-10 offset-lg-1">
              <div class="shadow mb-3 rounded text-white position-relative" style="background-color: <%= activity_css_rgba(activity) %>">
                <div class="p-3 rounded d-flex justify-content-between flex-sm-row flex-column" style="background-color: rgba(0,0,0,0.5)">
                  <div class="display-4">
                    <%= activity_verb_past_helper(activity.activity_type.name).capitalize %>
                    on <%= DateTime.parse(activity.start_time.to_s).strftime("%B %d") %>
                    at <%= activity.start_time.to_s(:time) %>
                  </div>

                  <div class="d-flex align-items-center">
                    <%= link_to 'Details', activity, class: "btn btn-md btn-info d-inline-block stretched-link" %>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>  <!-- container -->

      <% end %>

    </div>  <!-- collapsed -->

  <% end %>


</div>

app/views/activities/edit.html.erb
<%# provide(:page_title, ' | Editing ' %>

<hgroup>
  <h1 class="text-right"><em>My <%= @activity.activity_type.name %>  Activity </em></h1>
</hgroup>

<div class="d-flex flex-column">

  <h1 class="display-4 text-center"><%= font_awesome_tag(@activity.activity_type.fa_icon, "10rem") %></h1>



  <%= bootstrap_form_with(model: @activity, layout: :horizontal, local: true) do |form| %>

    <% if @activity.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

        <ul>
          <% activity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <% if @activity.duration.nil? %>
      <%= form.hidden_field :duration, value: compute_duration(DateTime.now, @activity.start_time) %>

      <div class="field actions my-2">
        <%= form.submit "Stop Timer!", class: "btn btn-md btn-warning my-1 w-100" %>
      </div>
    <% else %>


      <div class="row btn-group btn-group-toggle my-2" data-toggle="buttons">
        <% @activity_types.each do |activity_type| %>
          <div class="col-sm-4  mb-2">
            <label class="btn btn-secondary w-100 h-100">
              <%= radio_button("activity", "activity_type_id", activity_type.id) %>
              <%= font_awesome_tag(activity_type.fa_icon, "2rem") %>
              <br/>
              <%= activity_type.name %>
            </label>
          </div>
        <% end %>
      </div>

      <div class="d-flex flex-column align-items-start justify-content-between">

        <%#= form.label :start_time %>
        <%= form.datetime_select :start_time, discard_year: true, wrapper_class: "w-75  h-50" %>
        <%#= form.month_field :start_time, discard_year: true %>
        <%#= form.time_field :start_time, discard_seconds: true %>

        <%#= form.label :duration %>
        <%#= form.time_select :duration %>
        <%#= form.text_field :duration %>
        <%= form.number_field :duration, min: 0, max: 7200, step: 5, maxlength: 3, wrapper_class: "w-75  h-50" %>

      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-md btn-warning w-100" %>
      </div>

    <% end %>

  <% end %>


<%= link_to 'Back', activities_path, class: "btn btn-md btn-info my-2" %>

app/views/activities/index.html.erb
<%# provide(:@activity.activity_type.name) %>

<hgroup>
  <h1 class="text-right"><em>Activities count: <%= @activities.count %></em></h1>
</hgroup>
<%= link_to 'Show By Category', activities_by_categories_path, class: "btn btn-md btn-info my-3 w-100" %>
<%= link_to 'New Activity', new_activity_path, class: "btn btn-md btn-success my-2 w-100" %>


<div class="d-flex flex-wrap">

  <%# @activities.each do |activity| %>
  <% @all_activities_same_date.each do |date, activities| %>
    <div class="container my-1">
      <h2 class="display-2"> <%= DateTime.parse(date).strftime("%B %d") %> </h2>
    </div>
    <% activities.each do |activity| %>
      <%# [r, g, b, a] = activity_color_rgba(activity) %>
      <div class="container mb-3">
        <div class="row">
          <div class="col-lg-10 offset-lg-1">
            <div class="shadow mb-3 rounded text-white position-relative" style="background-color: <%= activity_css_rgba(activity) %>">
              <div class="p-3 rounded d-flex justify-content-between flex-sm-row flex-column" style="background-color: rgba(0,0,0,0.5)">
                <div class="display-4"><%= font_awesome_tag(activity.activity_type.fa_icon, "10rem") %> <%= activity_verb_past_helper(activity.activity_type.name).capitalize %>
                  at <%= activity.start_time.to_s(:time) %></div>
                <div class="d-flex align-items-center">
                  <%= link_to 'Details', activity, class: "btn btn-md btn-info d-inline-block stretched-link" %>
                </div>
              </div>
            </div>

          </div>
        </div>

      </div>  <!-- container -->

    <% end %>
  <% end %>


</div>

app/views/activities/new.html.erb
<%# provide(:@activity.activity_type.name) %>

<hgroup>
  <h1 class="text-right"><em>Start a New Activity Now</em></h1>
</hgroup>

<div class="d-flex flex-column">


<%# <%= render 'form', activity: @activity %>

  <% activity = @activity %>

  <div class="d-flex flex-row">
    <%= bootstrap_form_with(model: activity, local: true) do |form| %>

      <% if activity.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

          <ul>
            <% activity.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row btn-group btn-group-toggle my-2" data-toggle="buttons">
        <% @activity_types.each do |activity_type| %>

          <div class="col-sm-4 mb-2">
            <label class="btn btn-success  w-100 h-100">
              <%= radio_button("activity", "activity_type_id", activity_type.id) %>
              <%= font_awesome_tag(activity_type.fa_icon, "2rem") %>
              <br/>
              <%= activity_type.name %>
            </label>
          </div>
        <% end %>

        <%= form.hidden_field :start_time, value: Time.now %>
        <%= form.hidden_field :duration, value: nil %>
      </div>


      <div class="row">
        <div class="col-lg-12">
          <%= form.submit "Start Timer!", class: "btn btn-md btn-primary w-100" %>
        </div>
      </div>


    <% end %>
  </div>  <!--d-flex -->

  <%= link_to 'Back', activities_path, class: "btn btn-md btn-info my-2" %>

app/views/activities/show.html.erb
<%# provide(:@activity.activity_type.name) %>



<div class="d-flex flex-column">


  <div class="container my-5">
    <% unless @activity.duration.nil? %>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="shadow mb-3 rounded text-white" style="background-image:url(<%= activity_picture_url(@activity.activity_type.name) %>); background-size: cover; background-position: center;">
            <div class="p-3 rounded d-flex justify-content-between flex-sm-row flex-column" style="background-color: rgba(0,0,0,0.5)">
              <div class="display-4"><%= font_awesome_tag(@activity.activity_type.fa_icon, "10rem") %> <%= @activity.activity_type.name %></div>
              <div class="d-flex align-items-center">
                <a href="#" class="btn btn-primary d-inline-block"><i class="fas fa-clock mr-2"></i> <%= pluralize(@activity.duration, 'minute') %>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>


    <div class="col-lg-10 offset-lg-1">
      <div class="row shadow rounded " style="background-color: rgba(0,0,0,0.5)">

        <div class="text-grey p-3">
          <hgroup>
            <h1 class="display-5 text-right">You <%= activity_verb_past_helper(@activity.activity_type.name) %>
              the <%= @activity.start_time.to_s(:short) %></h1>
            <h2 class="text-right"><small> You exercised for a whole <%= pluralize(@activity.duration, 'minute') %>
              . <%= activity_motivational_helper(@activity.duration) %></small></h2>
          </hgroup>
        </div>
      </div>
    </div>

  </div>



  <%= link_to 'Back', activities_path, class: "btn btn-md btn-info mb-2" %>
  <% unless @activity.duration.nil? %>
    <%= link_to 'Edit this Activity', edit_activity_path(@activity), class: "btn btn-md btn-warning  mb-2" %>
    <%= link_to 'Delete', @activity, class: "btn btn-sm btn-danger  mb-3", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

</div> <!-- d-flex -->